export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#12f8d7",
        "on-secondary-container": "#525151",
        "background": "#f7f7f2",
        "surface-tint": "#006859",
        "primary-dim": "#005a4d",
        "surface-container-high": "#e2e3dd",
        "outline": "#767773",
        "on-secondary-fixed": "#403f3f",
        "on-error": "#ffefee",
        "secondary-fixed-dim": "#d6d4d3",
        "on-primary-container": "#00594c",
        "surface-bright": "#f7f7f2",
        "on-primary": "#c2ffef",
        "tertiary": "#b80040",
        "on-primary-fixed": "#00443a",
        "primary-fixed-dim": "#00e8c9",
        "surface-container": "#e8e9e3",
        "tertiary-dim": "#a20037",
        "inverse-primary": "#26fedc",
        "on-background": "#2d2f2c",
        "secondary-dim": "#504f4f",
        "on-surface": "#2d2f2c",
        "inverse-surface": "#0d0f0c",
        "on-error-container": "#570008",
        "surface": "#f7f7f2",
        "error": "#b31b25",
        "inverse-on-surface": "#9c9d99",
        "outline-variant": "#adada9",
        "on-tertiary-fixed": "#39000e",
        "surface-dim": "#d3d5cf",
        "secondary-fixed": "#e5e2e1",
        "secondary": "#5c5b5b",
        "error-dim": "#9f0519",
        "secondary-container": "#e5e2e1",
        "tertiary-fixed": "#ff909e",
        "surface-variant": "#dcddd7",
        "on-secondary": "#f5f2f1",
        "primary": "#006859",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dcddd7",
        "on-tertiary": "#ffefef",
        "on-tertiary-fixed-variant": "#780027",
        "error-container": "#fb5151",
        "on-surface-variant": "#5a5c58",
        "primary-fixed": "#12f8d7",
        "on-secondary-fixed-variant": "#5c5b5b",
        "surface-container-low": "#f1f1ec",
        "on-tertiary-container": "#670020",
        "tertiary-fixed-dim": "#ff788c",
        "on-primary-fixed-variant": "#006455",
        "tertiary-container": "#ff909e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
